# Generated by Django 3.1.2 on 2020-10-04 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_plan_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
